# Пример иерархического конфига для препроцессинга

# Пути к исходным и выходным датасетам
input:
  sentiment_path: "data sets/microsoft_processed_text_with_time_and_sentiments.pkl"
  dow_jones_path: "data sets/df_dow_jones.pkl"
  gensim_path: "data sets/microsoft_processed_text_with_time_and_gensim.pkl"

preprocessing:
  resample_rule: '1d'
  fillna_method: 'ffill'
  tz_convert: null
  join_type: 'inner'
  percent_of_training: 0.7
  back: 7
  output_path: "data sets/data_to_paper_microsoft_case.pkl"
  scaler:
    feature_range:
      min: 0
      max: 1
